import { Bell, KeyRound, ShieldCheck, UserRound } from 'lucide-react'
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Button } from '../components/ui/Button'
import { useAuth } from '../context/AuthContext'
import { apiErrorMessage, changePassword, updateProfile } from '../services/api'

export function Profile() {
  const { user, refresh } = useAuth()
  const navigate = useNavigate()
  const [name, setName] = useState(user?.name ?? '')
  const [alerts, setAlerts] = useState(user?.highRiskAlerts ?? true)
  const [weekly, setWeekly] = useState(user?.weeklySummary ?? false)
  const [currentPassword, setCurrentPassword] = useState('')
  const [newPassword, setNewPassword] = useState('')
  const [message, setMessage] = useState('')
  const [error, setError] = useState('')
  const [saving, setSaving] = useState(false)
  const saveProfile = async () => { setMessage(''); setError(''); setSaving(true); try { await updateProfile({ name, highRiskAlerts: alerts, weeklySummary: weekly }); await refresh(); setMessage('Profile settings saved.') } catch (e) { setError(apiErrorMessage(e, 'Could not save profile.')) } finally { setSaving(false) } }
  const savePassword = async () => { setMessage(''); setError(''); if (newPassword.length < 10) { setError('New password must be at least 10 characters.'); return } setSaving(true); try { await changePassword({ currentPassword, newPassword }); setCurrentPassword(''); setNewPassword(''); await refresh(); navigate('/login', { replace: true, state: { passwordChanged: true } }) } catch (e) { setError(apiErrorMessage(e, 'Could not change password.')) } finally { setSaving(false) } }
  return <div className="mx-auto max-w-5xl"><div><div className="eyebrow">Account</div><h1 className="mt-2 text-3xl font-bold text-white">Profile & settings</h1><p className="mt-2 text-sm text-slate-500">Manage your identity, password and security notifications.</p></div>{(message || error) && <div className={`mt-6 rounded-xl border p-4 text-sm ${error ? 'border-rose-300/10 bg-rose-400/5 text-rose-200' : 'border-emerald-300/10 bg-emerald-400/5 text-emerald-200'}`}>{error || message}</div>}<div className="mt-8 grid gap-5 lg:grid-cols-2"><section className="panel p-6"><div className="flex items-center gap-3"><UserRound size={18} className="text-sky-300"/><h2 className="font-semibold text-white">Profile</h2></div><div className="mt-6 space-y-4"><label className="block text-xs font-medium text-slate-400">Name<input value={name} onChange={(e) => setName(e.target.value)} maxLength={80} className="mt-2 w-full rounded-xl border border-white/10 bg-white/[0.035] px-3 py-3 text-sm text-white outline-none focus:border-sky-300/30"/></label><div><div className="text-xs font-medium text-slate-400">Email</div><div className="mt-2 rounded-xl border border-white/5 bg-black/10 px-3 py-3 text-sm text-slate-500">{user?.email}</div></div><Button loading={saving} onClick={() => void saveProfile()}>Save profile</Button></div></section><section className="panel p-6"><div className="flex items-center gap-3"><KeyRound size={18} className="text-sky-300"/><h2 className="font-semibold text-white">Change password</h2></div><div className="mt-6 space-y-4"><label className="block text-xs font-medium text-slate-400">Current password<input value={currentPassword} onChange={(e) => setCurrentPassword(e.target.value)} type="password" className="mt-2 w-full rounded-xl border border-white/10 bg-white/[0.035] px-3 py-3 text-sm text-white outline-none focus:border-sky-300/30"/></label><label className="block text-xs font-medium text-slate-400">New password<input value={newPassword} onChange={(e) => setNewPassword(e.target.value)} type="password" minLength={10} maxLength={128} className="mt-2 w-full rounded-xl border border-white/10 bg-white/[0.035] px-3 py-3 text-sm text-white outline-none focus:border-sky-300/30"/></label><Button variant="secondary" loading={saving} onClick={() => void savePassword()}>Change password</Button></div></section><section className="panel p-6 lg:col-span-2"><div className="flex items-center gap-3"><Bell size={18} className="text-sky-300"/><h2 className="font-semibold text-white">Notifications</h2></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><Toggle title="High-risk scan alerts" enabled={alerts} onChange={setAlerts}/><Toggle title="Weekly security summary" enabled={weekly} onChange={setWeekly}/></div></section></div><div className="mt-5 flex items-center gap-2 text-xs text-slate-600"><ShieldCheck size={14} className="text-emerald-300"/> State-changing account actions require a CSRF-protected authenticated session.</div></div>
}
function Toggle({ title, enabled, onChange }: { title: string; enabled: boolean; onChange: (value: boolean) => void }) { return <button type="button" aria-pressed={enabled} onClick={() => onChange(!enabled)} className={`flex items-center justify-between rounded-xl border p-4 text-left transition ${enabled ? 'border-sky-300/[0.15] bg-sky-400/5' : 'border-white/[0.07] bg-white/[0.02]'}`}><span className="text-sm text-slate-300">{title}</span><span className={`relative h-6 w-11 rounded-full ${enabled ? 'bg-sky-400' : 'bg-slate-700'}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white transition ${enabled ? 'left-6' : 'left-1'}`}/></span></button> }
